[package]
name = "reversejp"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["ringsaturn <ringsaturn.me@gmail.com>"]
description = "ReverseJP is a Rust library for reverse geocoding in Japan."
homepage = "https://github.com/ringsaturn/reversejp"
repository = "https://github.com/ringsaturn/reversejp"
readme = "README.md"

[dependencies]
cities-json = "0.6.8"
geometry-rs = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rand = "0.9.0"
zip = "2.3.0"

[dev-dependencies]
criterion = "0.5"
lazy_static = "1.5.0"

[[bench]]
name = "jp_city_lookup"
harness = false
